[book]
src = "src"
manual = "manual"
title = "SUPERTITLE"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/TruCol/Solidity-Forge-Template"

[output.html.fold]
enable = true
